### ISSUE TITLE
"Absolute" Horizontal and Vertical lines still need to use one of existing coordinates

### ISSUE THREAD

**Issue by chrismurf** [nvictus/svgpath2mpl#4]
In the case of an 'absolute' horizontal line, you still need to use the existing Y value as the new Y value.
In the case of an 'absolute' vertical line, you still need to use the existing X value as the new X value.

This is different from most of the path elements, where "absolute" means that both the X and Y value should be used.

The following path will not be drawn correctly:
```xml
<path fill="#FF8080" stroke="#000000" stroke-width="5" d="M173.25,517V327l132-122l132,122v190"/>
```

This can be fixed by (for example) modifying parse_path as follows:
```python
...
        elif command == 'H':
            # Horizontal line.
            verts = np.r_[values, 0. if is_relative else current_point[1]]
            codes = COMMANDS[command]

        elif command == 'V':
            # Vertical line.
            verts = np.r_[0. if is_relative else current_point[0], values]
            codes = COMMANDS[command]
...
```

**Comment by nvictus** [comment]
Should be fixed now.
