### ISSUE TITLE
Missing portions rendering some shapes

### ISSUE THREAD

**Issue by jjmontesl** [nvictus/svgpath2mpl#8]
Hello.

I'm trying to render some SVGs like:  https://fontawesome.com/icons/ice-cream

But I get some strange behavior, as some areas are ignored. It seems the source path has self-intersections, so I wonder if svgpath2mpl handles them.

The path in that SVG is: `{'d': 'M368 160h-.94a144 144 0 1 0-286.12 0H80a48 48 0 0 0 0 96h288a48 48 0 0 0 0-96zM195.38 493.69a31.52 31.52 0 0 0 57.24 0L352 288H96z'}`.

![image](https://user-images.githubusercontent.com/2786867/115267856-f163f600-a139-11eb-9d90-9fcbf5782615.png)

Any insight is appreciated.

**Comment by nvictus** [comment]
There seems to still be issues with converting matplotlib's elliptical arc generation into correct paths (the `a`/`A` commands).

I played around and I think I may have resolved the issue. I'm going to try to add a notebook to test more arc scenarios to make sure I didn't miss anything. I'll make a PR shortly and you're welcome to test out more arc-containing SVGs.

**Comment by jjmontesl** [comment]
Works for me! I have replied to #9.
